const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const root = path.resolve(__dirname, '..', process.argv[2] || 'playable-preview');
function walk(dir) { return fs.readdirSync(dir, {withFileTypes:true}).flatMap(entry => {
  const file=path.join(dir,entry.name);
  return entry.isDirectory()?walk(file):[path.relative(root,file).replace(/\\/g,'/')];
}); }
const files = walk(root).filter(f=>f!=='sw.js').sort();
const hash = crypto.createHash('sha256');
hash.update('offline-cache-format-v2');
for (const file of files) { hash.update(file); hash.update(fs.readFileSync(path.join(root, file))); }
const version = hash.digest('hex').slice(0, 16);
fs.writeFileSync(path.join(root, 'sw.js'), `// Generated by scripts/build-offline.cjs; do not edit.\n
const PREFIX = 'mahjong-pocket-' + encodeURIComponent(self.registration.scope) + '-';
const CACHE = PREFIX + ${JSON.stringify(version)};
const FILES = ${JSON.stringify(files.map(f => './' + f))};
self.addEventListener('install', event => {
  event.waitUntil(caches.open(CACHE).then(cache => cache.addAll(FILES)));
  // Updates wait until all old app windows close; never reload an active hand.
});
self.addEventListener('activate', event => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter(k => k.startsWith(PREFIX) && k !== CACHE).map(k => caches.delete(k)));
    await self.clients.claim();
  })());
});
self.addEventListener('message', event => {
  if(event.data?.type !== 'CHECK_OFFLINE')return;
  event.waitUntil((async () => {
    const cache=await caches.open(CACHE);
    const ready=(await Promise.all(FILES.map(file=>cache.match(file)))).every(Boolean);
    event.ports[0]?.postMessage({ready,cache:CACHE});
  })());
});
self.addEventListener('fetch', event => {
  const url = new URL(event.request.url);
  if (event.request.method !== 'GET' || url.origin !== self.location.origin || !url.href.startsWith(self.registration.scope)) return;
  event.respondWith((async () => {
    const cache = await caches.open(CACHE);
    if (event.request.mode === 'navigate') return (await cache.match('./index.html')) || fetch(event.request);
    return (await cache.match(event.request)) || fetch(event.request);
  })());
});
`);
console.log(`Offline cache ${version}: ${files.length} local files`);
